### ISSUE TITLE
`why` only shows one path

### ISSUE THREAD

**Issue by ramirez7** [dustin/graphex#13]
If there are multiple, that would be useful to show too. Maybe with some `tree`-like output to help visualize it?

**Comment by dustin** [comment]
I'm not sure how to display this on the CLI, but I added a thing that will extract a subgraph containing all of the connectivity between two specific points on a graph.  You can drop that into Looking Glass.

We can show multiple paths either by extracting this subgraph and just iterating every path through it showing all of the import paths in batches or maybe something tree-like.  I'm not entirely sure how to do such a thing.  But if you want to, we have the technology.  :)

I went ahead and pushed it, but I was working through a bunch of fancy graph traversal things trying to figure out how to do this iteration when I realized that this is at least a good and useful first step.  And it seemed fairly straightforward.  I just take the intersection of the set of reachable nodes from the start point and then invert the edges and do the same thing with the destination node.  Then I just have that thing that can restrict graphs to that intersection.  Seems to work as expected.

The one annoying part of this is that we've got two `allDepsOn` and `allDepsOnWithKey` that both exist with different use cases.  I'm kind of annoyed by this, but I couldn't think of better names or a more sensible way to think about this.  Maybe you've got a good idea there.  :)

**Comment by dustin** [comment]
I think we've shipped a couple solutions to this.
